<?php defined('ABSPATH')||exit; $links=fuwari_navigation(); ?>
<div id="navbar" class="z-50 onload-animation"><div class="absolute h-8 left-0 right-0 -top-8 bg-[var(--card-bg)] transition"></div><div class="card-base !overflow-visible max-w-[var(--page-width)] h-[4.5rem] !rounded-t-none mx-auto flex items-center justify-between px-4">
<a href="<?php echo esc_url(home_url('/'));?>" class="btn-plain scale-animation rounded-lg h-[3.25rem] px-5 font-bold active:scale-95"><div class="flex flex-row text-[var(--primary)] items-center text-md"><?php echo fuwari_icon('material-symbols:home-outline-rounded','text-[1.75rem] mb-1 mr-2');?><?php bloginfo('name');?></div></a>
<div class="hidden md:flex"><?php foreach($links as $link):?><a href="<?php echo esc_url($link['url']);?>" class="btn-plain scale-animation rounded-lg h-11 font-bold px-5 active:scale-95" <?php if(!empty($link['external']))echo 'target="_blank" rel="noopener"';?>><div class="flex items-center"><?php echo !empty($link['key'])?fuwari_label($link['key']):esc_html($link['name']);?><?php if(!empty($link['external']))echo fuwari_icon('fa6-solid:arrow-up-right-from-square','text-[0.875rem] transition -translate-y-[1px] ml-1 text-black/[0.2] dark:text-white/[0.2]');?></div></a><?php endforeach;?></div>
<div class="flex"><div id="search-bar" class="hidden lg:flex transition-all items-center h-11 mr-2 rounded-lg bg-black/[0.04] hover:bg-black/[0.06] focus-within:bg-black/[0.06] dark:bg-white/5 dark:hover:bg-white/10 dark:focus-within:bg-white/10 relative"><?php echo fuwari_icon('material-symbols:search','absolute text-[1.25rem] pointer-events-none ml-3 transition my-auto text-black/30 dark:text-white/30');?><input class="fuwari-search transition-all pl-10 text-sm bg-transparent outline-0 h-full w-40 active:w-60 focus:w-60 text-black/50 dark:text-white/50" type="search" placeholder="<?php echo esc_attr(fuwari_t('search'));?>" aria-label="<?php echo esc_attr(fuwari_t('search'));?>" data-i18n-placeholder="search"></div>
<button id="search-switch" class="btn-plain scale-animation lg:!hidden rounded-lg w-11 h-11 active:scale-90" aria-label="<?php echo esc_attr(fuwari_t('search'));?>"><?php echo fuwari_icon('material-symbols:search','text-[1.25rem]');?></button>
<?php if(fuwari_option('visitor_color')||fuwari_option('visitor_language')):?><button id="display-settings-switch" aria-label="<?php echo esc_attr(fuwari_t('displaySettings'));?>" class="btn-plain scale-animation rounded-lg h-11 w-11 active:scale-90"><?php echo fuwari_icon('material-symbols:palette-outline','text-[1.25rem]');?></button><?php endif;?>
<div class="relative"><button id="scheme-switch" aria-label="<?php echo esc_attr(fuwari_t('colorMode'));?>" class="btn-plain scale-animation rounded-lg h-11 w-11 active:scale-90"><?php foreach(['light'=>'material-symbols:light-mode-outline-rounded','dark'=>'material-symbols:dark-mode-outline-rounded','system'=>'fa6-solid:circle-half-stroke'] as $mode=>$icon):?><span data-mode-icon="<?php echo $mode;?>" class="<?php if($mode!==fuwari_option('theme_mode'))echo 'hidden';?>"><?php echo fuwari_icon($icon,'text-[1.25rem]');?></span><?php endforeach;?></button><div id="light-dark-panel" class="float-panel float-panel-closed absolute top-14 right-0 p-2 rounded-xl w-40 shadow-xl"><?php foreach(['light'=>'material-symbols:light-mode-outline-rounded','dark'=>'material-symbols:dark-mode-outline-rounded','system'=>'fa6-solid:circle-half-stroke'] as $mode=>$icon):?><button data-theme="<?php echo $mode;?>" class="btn-plain rounded-lg w-full h-9 px-3 !justify-start font-medium"><?php echo fuwari_icon($icon,'text-[1.25rem] mr-3');?><?php echo fuwari_label($mode);?></button><?php endforeach;?></div></div>
<button id="nav-menu-switch" aria-label="<?php echo esc_attr(fuwari_t('menu'));?>" class="btn-plain scale-animation rounded-lg w-11 h-11 active:scale-90 md:!hidden"><?php echo fuwari_icon('material-symbols:menu-rounded','text-[1.25rem]');?></button></div>
<div id="nav-menu-panel" class="float-panel float-panel-closed absolute top-20 left-4 right-4 p-2 rounded-2xl shadow-xl md:hidden"><?php foreach($links as $link):?><a class="btn-plain px-3 py-2 rounded-lg !justify-start" href="<?php echo esc_url($link['url']);?>"><?php echo !empty($link['key'])?fuwari_label($link['key']):esc_html($link['name']);?></a><?php endforeach;?></div>
<div id="display-setting" class="float-panel float-panel-closed absolute top-20 right-4 p-4 rounded-2xl shadow-xl w-72">
<?php if(fuwari_option('visitor_color')):?><div class="flex gap-2 mb-3 items-center justify-between"><div class="flex gap-2 font-bold text-lg text-neutral-900 dark:text-neutral-100 transition relative ml-3 before:w-1 before:h-4 before:rounded-md before:bg-[var(--primary)] before:absolute before:-left-3 before:top-[0.33rem]"><?php echo fuwari_label('themeColor');?><button id="hue-reset" aria-label="<?php echo esc_attr(fuwari_t('reset'));?>" class="btn-regular w-7 h-7 rounded-md opacity-0 pointer-events-none"><?php echo fuwari_icon('fa6-solid:arrow-rotate-left','text-[0.875rem]');?></button></div><div id="hue-value" class="transition bg-[var(--btn-regular-bg)] w-10 h-7 rounded-md flex justify-center font-bold text-sm items-center text-[var(--btn-content)]"><?php echo (int)fuwari_option('hue');?></div></div><div class="w-full h-6 px-1 rounded select-none fuwari-color-track"><input id="colorSlider" class="w-full slider" type="range" min="0" max="360" step="5" value="<?php echo (int)fuwari_option('hue');?>" aria-label="<?php echo esc_attr(fuwari_t('themeColor'));?>"></div><?php endif;?>
<?php if(fuwari_option('visitor_language')):?><div class="font-bold mt-4 mb-2"><?php echo fuwari_label('language');?></div><div class="flex gap-2"><button class="btn-regular rounded-lg px-3 py-2" data-language="zh_CN">简体中文</button><button class="btn-regular rounded-lg px-3 py-2" data-language="en">English</button></div><?php endif;?></div>
<div id="search-panel" class="float-panel float-panel-closed search-panel absolute md:w-[30rem] top-20 left-4 md:left-[unset] right-4 shadow-2xl rounded-2xl p-2"><div class="lg:hidden p-2"><input class="fuwari-search w-full h-11 rounded-xl bg-black/[0.04] dark:bg-white/5 px-3 outline-0" type="search" placeholder="<?php echo esc_attr(fuwari_t('search'));?>" data-i18n-placeholder="search" aria-label="<?php echo esc_attr(fuwari_t('search'));?>"></div><div id="search-results" aria-live="polite"></div><noscript><form action="<?php echo esc_url(home_url('/'));?>"><input name="s" type="search"><button><?php echo esc_html(fuwari_t('search'));?></button></form></noscript></div>
</div></div>
