<?php defined('ABSPATH')||exit; $banner=(bool)fuwari_option('banner_enable'); ?>
<!doctype html><html lang="<?php echo fuwari_language()==='en'?'en':'zh-CN'; ?>" class="bg-[var(--page-bg)] transition text-[14px] md:text-[16px]" data-overlayscrollbars-initialize><head><meta charset="<?php bloginfo('charset');?>"><meta name="viewport" content="width=device-width,initial-scale=1"><?php fuwari_head_config();wp_head();?></head>
<body <?php body_class('min-h-screen transition '.($banner?'enable-banner ':'').(is_home()?'lg:is-home is-home':''));?> data-overlayscrollbars-initialize>
<?php wp_body_open(); ?>
<div id="site-shell">
<div id="top-row" class="z-50 pointer-events-none relative transition-all duration-700 max-w-[var(--page-width)] px-0 md:px-4 mx-auto"><div id="navbar-wrapper" class="pointer-events-auto sticky top-0 transition-all"><?php get_template_part('parts/navbar');?></div></div>
<?php if($banner):?><div id="banner-wrapper" class="absolute z-10 w-full transition duration-700 overflow-hidden" style="top:-<?php echo max(0,(int)fuwari_option('banner_home_height')-(int)fuwari_option('banner_height'));?>vh"><div id="banner" class="object-cover h-full transition duration-700 opacity-0 scale-105"><img alt="" fetchpriority="high" src="<?php echo esc_url(fuwari_option('banner_image')?:fuwari_asset('images/demo-banner.png','css',true));?>" style="object-position:<?php echo esc_attr(fuwari_option('banner_position'));?>" class="w-full h-full object-cover"></div></div><?php endif;?>
<div class="w-full z-30 pointer-events-none" id="main-panel"><div class="fuwari-main-inner relative max-w-[var(--page-width)] mx-auto pointer-events-auto"><div id="main-grid" class="transition duration-700 w-full left-0 right-0 grid grid-cols-[17.5rem_auto] grid-rows-[auto_1fr_auto] lg:grid-rows-[auto] mx-auto gap-4 px-0 md:px-4">
<?php if($banner&&fuwari_option('banner_credit_enable')):?><a id="banner-credit" class="group onload-animation transition-all absolute flex justify-center items-center rounded-full px-3 right-4 -top-[3.25rem] bg-black/60 hover:bg-black/70 h-9" href="<?php echo esc_url(fuwari_option('banner_credit_url')?:'#');?>" target="_blank" rel="noopener"><?php echo fuwari_icon('material-symbols:copyright-outline-rounded','text-white/75 text-[1.25rem] mr-1');?><span class="text-white/75 text-xs"><?php echo esc_html(fuwari_option('banner_credit'));?></span></a><?php endif;?>
<?php get_sidebar();?><main id="swup-container" class="transition-swup-fade col-span-2 lg:col-span-1 overflow-hidden"><div id="content-wrapper" class="onload-animation">
