<?php defined('ABSPATH')||exit;get_header();while(have_posts()):the_post();$post=get_post();$reading=fuwari_reading($post);?>
<div class="flex w-full rounded-[var(--radius-large)] overflow-hidden relative mb-4"><article id="post-container" class="card-base z-10 px-6 md:px-9 pt-6 pb-4 relative w-full">
<div class="flex flex-row text-black/30 dark:text-white/30 gap-5 mb-3 transition onload-animation"><div class="flex flex-row items-center"><div class="transition h-6 w-6 rounded-md bg-black/5 dark:bg-white/10 text-black/50 dark:text-white/50 flex items-center justify-center mr-2"><?php echo fuwari_icon('material-symbols:notes-rounded');?></div><div class="text-sm"><?php echo $reading['words'].' '.fuwari_label($reading['words']===1?'word':'words');?></div></div><div class="flex flex-row items-center"><div class="transition h-6 w-6 rounded-md bg-black/5 dark:bg-white/10 text-black/50 dark:text-white/50 flex items-center justify-center mr-2"><?php echo fuwari_icon('material-symbols:schedule-outline-rounded');?></div><div class="text-sm"><?php echo $reading['minutes'].' '.fuwari_label($reading['minutes']===1?'minute':'minutes');?></div></div></div>
<div class="relative onload-animation"><h1 class="transition w-full block font-bold mb-3 text-3xl md:text-[2.25rem]/[2.75rem] text-black/90 dark:text-white/90 md:before:w-1 before:h-5 before:rounded-md before:bg-[var(--primary)] before:absolute before:top-[0.75rem] before:left-[-1.125rem]"><?php the_title();?></h1></div>
<div class="onload-animation"><?php fuwari_metadata($post,'mb-5');if(!has_post_thumbnail()):?><div class="border-[var(--line-divider)] border-dashed border-b-[1px] mb-5"></div><?php endif;?></div>
<?php if(has_post_thumbnail())the_post_thumbnail('full',['class'=>'w-full mb-8 rounded-xl onload-animation']);?>
<div class="prose dark:prose-invert prose-base !max-w-none custom-md mb-6 markdown-content onload-animation" lang="<?php echo esc_attr(get_post_meta(get_the_ID(),'_fuwari_language',true)?:get_bloginfo('language'));?>"><?php the_content();?></div>
<?php if(fuwari_option('license_enable')):?><div class="fuwari-license mb-6 rounded-xl onload-animation"><div class="font-bold text-75"><?php the_title();?></div><a class="link text-[var(--primary)]" href="<?php the_permalink();?>"><?php the_permalink();?></a><div class="fuwari-license-details"><div><div class="text-sm text-30"><?php echo fuwari_label('author');?></div><div class="text-75"><?php echo esc_html(fuwari_option('profile_name'));?></div></div><div><div class="text-sm text-30"><?php echo fuwari_label('publishedAt');?></div><div class="text-75"><?php echo get_the_date('Y-m-d');?></div></div><div><div class="text-sm text-30"><?php echo fuwari_label('license');?></div><a class="link text-[var(--primary)]" href="<?php echo esc_url(fuwari_option('license_url'));?>" target="_blank" rel="noopener"><?php echo esc_html(fuwari_option('license_name'));?></a></div></div><?php echo fuwari_icon('fa6-brands:creative-commons','fuwari-license-symbol');?></div><?php endif;?>
<?php if(fuwari_option('comments_enable')&&(comments_open()||get_comments_number()))comments_template();?></article></div>
<nav class="flex flex-col md:flex-row justify-between mb-4 gap-4 overflow-hidden w-full"><?php $previous=get_previous_post();$next=get_next_post();foreach([[$previous,'left'],[$next,'right']] as [$adjacent,$direction]):?><div class="w-full"><?php if($adjacent):?><a class="btn-card rounded-2xl w-full h-[3.75rem] px-4 gap-4 font-bold" href="<?php echo esc_url(get_permalink($adjacent));?>"><?php if($direction==='left')echo fuwari_icon('material-symbols:chevron-left-rounded','text-[2rem] text-[var(--primary)]');?><span class="overflow-hidden overflow-ellipsis whitespace-nowrap text-black/75 dark:text-white/75"><?php echo esc_html(get_the_title($adjacent));?></span><?php if($direction==='right')echo fuwari_icon('material-symbols:chevron-right-rounded','text-[2rem] text-[var(--primary)]');?></a><?php endif;?></div><?php endforeach;?></nav>
<?php endwhile;get_footer();?>
